spring:
  datasource:
    url: jdbc:mysql://${SERVER_IP}:${DB_PORT}/vpp
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8000